=== Souniz/master1/S1/web_des_donnees/TP2/heros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="heros" type="Heros"/>
<xsd:complexType name="Heros">
    <xsd:sequence>
        <xsd:element name="powers" type="Powers" minOccurs="1"/>
        <xsd:element name="hero" type="Hero" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>
<xsd:complexType name="Powers">
    <xsd:sequence>
        <xsd:element name="power" type="Power" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>
<xsd:complexType name="Hero">
    <xsd:sequence>
        <xsd:element name="identity" type="Identity"/>
        <xsd:element name="species" type="xsd:string"/>
        <xsd:element name="abilities" type="xsd:string"/>
        <xsd:element name="movies" type="Movies"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="birth-year" type="xsd:gYear"/>
</xsd:complexType>
<xsd:complexType name="Power">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="id" type="xsd:string"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>
<xsd:complexType name="Identity">
    <xsd:sequence>
        <xsd:element name="firstname" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
        <xsd:element name="lastname" type="xsd:string" maxOccurs="1" minOccurs="1"/>
        <xsd:choice>
            <xsd:element name="aliases" type="Aliases"/>
            <xsd:element name="alias" type="xsd:string" maxOccurs="unbounded"/>
        </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="height" type="Height"/>
    <xsd:attribute name="genre" type="Genre"/>
</xsd:complexType>
<xsd:complexType name="Aliases">
    <xsd:sequence>
        <xsd:element name="alias" type="xsd:string" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>
<xsd:simpleType name="Genre">
    <xsd:restriction base="xsd:string">
       <xsd:enumeration value="F"/>
       <xsd:enumeration value="M"/>
       <xsd:enumeration value="NA"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="Movies">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="([a-zA-Z0-9_]+\[[0-9]{4}\]\s?)+"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="Height">
    <xsd:restriction base="xsd:decimal">
        <xsd:pattern value="[0-9]{1}.[0-9]{2}"/>
    </xsd:restriction>
</xsd:simpleType>
</xsd:schema>

=== Souniz/master1/web_des_donnees/TP2/heros.xml
<?xml version='1.0' encoding='UTF-8'?>
<heros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="heros.xsd">
	<powers>
		<power id="aucun">aucun pouvoir</power>
		<power id="colle">Pouvoir de d’adhérence aux murs, plafonds et autres objets similaire à celui des araignées.</power>
		<power id="voler">Pouvoir de voler dans les airs.</power>
		<power id="force">Force physique surhumaine.</power>
		<power id="precognition">Pouvoir de perception extrasensorielle permettant la prévision d'événements futurs non déductibles de la connaissance du présent.</power>
	</powers>
	<hero id="h-001" birth-year="1962">
		<identity height="2.78" genre="M">
			<firstname>Peter</firstname>
			<firstname>Benjamin</firstname>
			<lastname>PARKER</lastname>
			<aliases>
				<alias>Spider Man</alias>
				<alias>L'homme araignée</alias>
				<alias>Spidey</alias>
			</aliases>
		</identity>
		<species>Mutant</species>
		<abilities>colle force precognition</abilities>
		<movies>iron_man_2[2010] venom[2021] spider_man[2021]</movies>
	</hero>
	<hero id="h-002" birth-year="1915">
		<identity>
			<firstname>Bruce</firstname>
			<lastname>WAYNE</lastname>
			<aliases>
				<alias>Batman</alias>
				<alias>Dark Knight</alias>
			</aliases>
		</identity>
		<species>Humain</species>
		<abilities>aucun</abilities>
		<movies>the_batman[2022] batman_vs_superman[2016]</movies>
	</hero>
	<hero id="h-003" birth-year="1932">
		<identity height="1.90">
			<firstname>Clark</firstname>
			<firstname>Joseph</firstname>
			<lastname>Kent</lastname>
			<alias>Superman</alias>
		</identity>
		<species>Kryptonien</species>
		<abilities>vitesse voler force</abilities>
		<movies>man_of_steel[2013] justice_league[2017] batman_vs_superman[2016]</movies>
	</hero>
</heros>
